image: Visual Studio 2017

platform:
  - x64

environment:
  matrix:
    - nodejs_version: 10

cache:
  - '%LOCALAPPDATA%/Yarn'
  - node_modules
  - app/node_modules
  - flow-typed
  - '%USERPROFILE%\.electron'

matrix:
  fast_finish: true

build: off

version: '{build}'

shallow_clone: true

clone_depth: 1

install:
  - ps: Install-Product node $env:nodejs_version x64
  - set CI=true
  - yarn

test_script:
  - yarn package-ci
  - yarn lint
  # - yarn flow
  - yarn test
  - yarn build-e2e
  # - yarn test-e2e
