os: unstable

environment:
  matrix:
    - nodejs_version: 7
    - nodejs_version: 6

cache:
  - node_modules -> package.json
  - app/node_modules -> app/package.json

# Enable when https://github.com/yarnpkg/yarn/issues/1233 and
# https://github.com/yarnpkg/yarn/issues/1059 are resolved and disable npm cache
#
# cache:
#   - "%LOCALAPPDATA%/Yarn"

matrix:
  fast_finish: true

build: off

version: '{build}'

shallow_clone: true

clone_depth: 1

install:
  - ps: Install-Product node $env:nodejs_version
  - set CI=true
  - npm install -g npm@latest
  - set PATH=%APPDATA%\npm;%PATH%
  - npm install

# Enable when https://github.com/yarnpkg/yarn/issues/1233 and
# https://github.com/yarnpkg/yarn/issues/1059 are resolved and disable npm cache
#
# install:
#   - ps: Install-Product node $env:nodejs_version
#   - set CI=true
#   - choco install yarn
#   - refreshenv
#   - yarn

script:
  - npm run test-all
  - npm run package
